function log_trial_data(trial_idx, run_idx, trial_data, filename)
% Appends trial data to the specified CSV file.

    fid = fopen(filename, 'a'); % Open in append mode
    fprintf(fid, '%d,%d,%s,%d,%.2f,%.2f,%s,%.4f,%.2f,%.4f,%.4f\n', ...
            run_idx, trial_idx, trial_data.gamble_type, trial_data.num_cups, ...
            trial_data.gain_amount, trial_data.loss_amount, trial_data.choice, ...
            trial_data.rt, trial_data.outcome, ...
            trial_data.decision_stim_onset, trial_data.feedback_onset);
    fclose(fid);
end